baseURL = 'https://lew-cloud.github.io/'
languageCode = 'zh-cn'
title = 'lew blog'
theme = "nightfall"
[params.styles]
color = "pink"
[params]
user = "lew"
hostname = "github.io"

  [params.author]
    name = "Lew's Blog"
    email = "julianlew9@gmail.com"
    avatarFirst = false
[menu]
  [[menu.header]]
    name = "posts"
    weight = 1
    url = "/posts"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"
