baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'lew blog'
theme = "nightfall"
[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'
[params.styles]
color = "pink"
[params]
user = "lew"
hostname = "oomkill.io"

  [params.author]
    name = "Lew's Blog"
    email = "hugo@example.com"
    avatarFirst = false
[menu]
  [[menu.header]]
    name = "posts"
    weight = 1
    url = "/posts"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"
